name: sloppy-labwork
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.3
  - pip
  - pip:
    - Django==3.0.7
    - Markdown==3.2.2
    - Pillow==7.1.2
    - boto3==1.13.16
    - django-allauth==0.41
    - django-heroku==0.3.1
    - gunicorn==20.0.4
    - psycopg2-binary==2.8.5
    - requests
    - sendgrid==6.4.4
    - opencv-python-headless==4.5