name: sloppy-labwork
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.2
  - pip
  - pip:
    - Django==3.0
    - django-allauth==0.41
    - gunicorn==20.0.4
    - django-heroku==0.3.1
    - Markdown==3.2.2
    - psycopg2-binary==2.8.5
    - requests