name: sloppy-labwork
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.3
  - pip
  - pip:
    - Django==3.0.1
    - django-allauth==0.41
    - gunicorn==20.0.4
    - django-heroku==0.3.1
    - Markdown==3.2.2
    - psycopg2-binary==2.8.5
    - boto3==1.13.16
    - Pillow==7.1.2
    - requests